version: 2

models:
  - name: dim_customers
    description: "Table de dimension des clients"
    columns:
      - name: customer_id
        description: "Clé primaire du client"
        tests:
          - unique
          - not_null

  - name: dim_products
    description: "Table de dimension des produits"
    columns:
      - name: product_id
        description: "Clé primaire du produit"
        tests:
          - unique
          - not_null

  - name: fct_orders
    description: "Table de faits des commandes e-commerce"
    columns:
      - name: order_id
        description: "Clé primaire de la commande"
        tests:
          - unique
          - not_null

      - name: customer_id
        description: "Clé étrangère vers la dimension client"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id